FROM node:22-slim

WORKDIR /node

# 使用淘宝源的同时安装 pnpm（避免 npm bug）
RUN npm config set registry https://registry.npmmirror.com \
    && npm install -g pnpm

# 拷贝项目文件
COPY web .

# 使用 pnpm 安装依赖（不会出现 rollup optionalDependencies 的 bug）
RUN pnpm install

# 设置环境变量
ENV HOST=0.0.0.0
ENV PORT=8084
ENV API_URL=http://server:8091

# 使用开发模式运行
CMD ["pnpm", "run", "dev"]
